repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [--line-length=132]
    -   id: ruff-format
        args: [--line-length=132]
-   repo: local
    hooks:
    -   id: pytest-unit
        name: pytest (unit tests)
        entry: python scripts/test_unit.py
        language: system
        pass_filenames: false
        always_run: true