name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  installation-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4
    
    # https://github.com/actions/setup-python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    # https://github.com/astral-sh/setup-uv
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
    
    # Install project dependencies with UV
    - name: Install dependencies with UV
      run: |
        uv pip install --system ".[dev]"
    
    # Verify core dependencies are properly installed
    - name: Verify installation
      run: |
        python -c "import crewai; import langchain; import pydantic; print('All core dependencies installed successfully')" 